### ISSUE TITLE
Reduce unused CSS？

### ISSUE THREAD

**Issue by sgalcheung** [jfcherng/Noto-Sans-SC-CSS#16]
I used this font in my repo and Lighthouse Diagnostics' “Reduce unused CSS - Potential savings of 34 KiB”
![image](https://github.com/user-attachments/assets/07e8a095-93f7-4e88-a1c0-756b131e81cb)

According to the coverage show, this is the main reason that it is using the font
![image](https://github.com/user-attachments/assets/63f67bac-8ae1-4286-976e-90dacb93c1b1)

In my project, I used the font this way
`import "noto-sans-sc/noto_sans_sc_regular/css.css";`

and is this the right way?

**Comment by jfcherng** [comment]
In my opinion, unless you can know exact which characters/words you will use beforehand, there is no way to reduce the CSS you include. 

> In my project, I used the font this way import "noto-sans-sc/noto_sans_sc_regular/css.css"; and is this the right way?

yes

**Comment by sgalcheung** [comment]
Do you mean 'Font Subset'? but Google Fonts is working to optimize the [font-slicing system](https://developers.googleblog.com/en/google-fonts-launches-japanese-support/).
Google provide fonts, such as [Noto-Sans-SC](https://fonts.google.com/share?selection.family=Noto+Sans+SC:wght@100..900) not slicing?

According to the article, I think this is the solution they adopted to support CJK fonts.


参考 [Google Fonts 加持的高级中文字体子集化实现](https://blog.dsrkafuu.net/post/2022/google-fonts-subsetting/)

**Comment by jfcherng** [comment]
> Do you mean 'Font Subset'? but Google Fonts is working to optimize the [font-slicing system](https://developers.googleblog.com/en/google-fonts-launches-japanese-support/).
Google provide fonts, such as [Noto-Sans-SC](https://fonts.google.com/share?selection.family=Noto+Sans+SC:wght@100..900) not slicing?

The one you used here is sliced. As you can see in https://github.com/jfcherng/Noto-Sans-SC-CSS/blob/master/noto_sans_sc_regular/css.css

However, it results in a big CSS file (100KB), which your tool complains. But obviously it's dramatically smaller than loading a full set Chinese font at once. 

What I said is that there are many slices as you can see in https://github.com/jfcherng/Noto-Sans-SC-CSS/tree/master/noto_sans_sc_regular. Unless you know certain slices won't be used in your project beforehand, otherwise there is no way to make the CSS (just a little bit) smaller by removing unused slices.

**Comment by sgalcheung** [comment]
Thank you explain this, Google already sliced font, but how to use depends on the user.
and can we offer a subsetted font, like [MiSans (subsetted) fonts](https://github.com/dsrkafuu/misans)?

**Comment by jfcherng** [comment]
Not sure what you mean, it's SC already here.

**Comment by sgalcheung** [comment]
Oh, I think I'm wrong, Xiaomi office does not SC of MiSans font, so [MiSans (subsetted) fonts](https://github.com/dsrkafuu/misans) did.

**Comment by jfcherng** [comment]
Assuming issue resolved.
